name: HelloIPA
options:
  bundleIdPrefix: com.m3sb
  deploymentTarget:
    iOS: "15.0"
targets:
  HelloIPA:
    type: application
    platform: iOS
    sources:
      - HelloIPA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.passionfruit5910.lavender4318
        INFOPLIST_FILE: HelloIPA/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: Hello IPA
        INFOPLIST_KEY_M3SB_API_BASE_URL: https://api.m3sbapi.shop
        INFOPLIST_KEY_M3SB_HMAC_SECRET: $(M3SB_HMAC_SECRET)
        INFOPLIST_KEY_LSRequiresIPhoneOS: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
