name: HelloIPA
options:
  bundleIdPrefix: com.m3sb
  deploymentTarget:
    iOS: "15.0"
targets:
  HelloIPA:
    type: application
    platform: iOS
    sources:
      - HelloIPA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.m3sb.demoipa
        INFOPLIST_KEY_CFBundleDisplayName: Hello IPA
        INFOPLIST_KEY_LSRequiresIPhoneOS: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
